### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by chris-zeitport** [enhance-dev/enhance-starter-project#9]
This repository does not contain any license information.

- Add a LICENSE file
- Update repo
- Add license property to `package.json`

See also:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Since this is a starter project I would recommend using MIT

**Comment by kristoferjoseph** [comment]
This is an interesting topic for sure.
Since this is generated for a user we had hoped that the user would add their own.
I can totally get behind adding one to this repo to assuage any fears users might have that we would add any kind of negative licensing at a later date.
We would most likely add Apache licensing since it is the most defensible.

Thoughts @brianleroux ?
